"use client";

import { useAdminStore } from "@/store/useAdminStore";
import {
  ArrowLeft,
  Sparkles,
  Download,
  Share2,
  CheckCircle,
  ShieldAlert,
  AlertCircle,
  Loader2,
} from "lucide-react";
import Link from "next/link";
import { useEffect } from "react";

interface PolicyBriefDetailPageProps {
  params: {
    id: string;
  };
}

export default function PolicyBriefDetailPage({
  params,
}: PolicyBriefDetailPageProps) {
  const {
    selectedBrief,
    error,
    isLoadingBriefs,
    fetchBriefDetail,
    clearSelectedBrief,
  } = useAdminStore();

  useEffect(() => {
    fetchBriefDetail(params.id).catch(() => {});

    return () => {
      clearSelectedBrief();
    };
  }, [params.id, fetchBriefDetail, clearSelectedBrief]);

  if (isLoadingBriefs) {
    return (
      <div className="flex min-h-[400px] items-center justify-center text-sm text-gray-500">
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
        Memuat policy brief...
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
        {error}
      </div>
    );
  }

  if (!selectedBrief) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-8 text-center text-sm text-gray-500">
        Policy brief tidak ditemukan.
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <Link
          href="/admin/laporan"
          className="flex items-center gap-2 text-sm font-medium text-gray-500 transition-colors hover:text-gray-900"
        >
          <ArrowLeft className="h-4 w-4" />
          Kembali ke Laporan Analitik
        </Link>

        <div className="flex items-center gap-3">
          <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">
            {selectedBrief.urgency_classification}
          </span>

          <span className="flex items-center gap-1 text-xs text-gray-400">
            <Sparkles className="h-3 w-3" />
            Generated by {selectedBrief.generated_by}
          </span>
        </div>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-10 shadow-sm md:p-16">
        <div className="mb-8 border-b-2 border-gray-900 pb-6 text-center">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-lg bg-gray-200">
            <ShieldAlert className="h-8 w-8 text-gray-500" />
          </div>

          <h2 className="text-xl font-bold tracking-wide text-gray-900 uppercase">
            Pemerintah Republik Indonesia
          </h2>

          <h3 className="text-primary mt-1 text-lg font-bold tracking-wide uppercase">
            Pusat Analisis Data Aspirasi Publik Vokara
          </h3>

          <p className="mt-2 text-sm text-gray-500">
            Sistem Terintegrasi Kebijakan Berbasis Bukti Digital
          </p>
        </div>

        <h1 className="border-primary mb-6 border-l-4 pl-4 text-2xl leading-snug font-bold text-gray-900 md:text-3xl">
          Brief Kebijakan Cluster {selectedBrief.cluster_id.slice(0, 8)}
        </h1>

        <div className="mb-10 flex flex-wrap gap-6 text-sm font-medium text-gray-600">
          <p>Nomor: {selectedBrief.id.slice(0, 8).toUpperCase()}</p>

          <p>
            Tanggal:{" "}
            {new Date(selectedBrief.generated_at).toLocaleDateString("id-ID")}
          </p>

          <p>
            Sifat:{" "}
            <span className="font-bold text-red-600">
              {selectedBrief.urgency_classification}
            </span>
          </p>
        </div>

        <div className="bg-primary/5 border-primary/20 mb-10 rounded-xl border p-6">
          <h3 className="text-primary mb-3 flex items-center gap-2 text-lg font-bold">
            <Sparkles className="h-5 w-5" />
            Ringkasan Eksekutif
          </h3>

          <p className="text-sm leading-relaxed whitespace-pre-line text-gray-700">
            {selectedBrief.content}
          </p>
        </div>

        <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-gray-900">
          <AlertCircle className="h-5 w-5 text-gray-400" />
          Informasi Brief
        </h3>

        <div className="mb-10 grid grid-cols-1 gap-4 md:grid-cols-2">
          <InfoCard
            title="Cluster ID"
            value={selectedBrief.cluster_id.slice(0, 8)}
            desc="Cluster sumber analisis kebijakan."
          />

          <InfoCard
            title="Urgensi"
            value={selectedBrief.urgency_classification}
            desc="Klasifikasi urgensi hasil analisis sistem."
          />

          <InfoCard
            title="Generator"
            value={selectedBrief.generated_by}
            desc="Pihak atau sistem pembuat policy brief."
          />

          <InfoCard
            title="Tanggal"
            value={new Date(selectedBrief.generated_at).toLocaleDateString(
              "id-ID",
            )}
            desc="Waktu policy brief dibuat."
          />
        </div>

        <h3 className="mb-4 flex items-center gap-2 text-lg font-bold text-gray-900">
          <CheckCircle className="h-5 w-5 text-gray-400" />
          Tindak Lanjut
        </h3>

        <div className="mb-10 space-y-4">
          {[
            "Verifikasi cluster dan sampel aspirasi terkait.",
            "Kirim brief kepada instansi yang berwenang.",
            "Pantau perubahan status aspirasi setelah tindak lanjut.",
          ].map((item, idx) => (
            <div key={item} className="flex items-start gap-4">
              <div className="bg-primary/10 text-primary flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-bold">
                {idx + 1}
              </div>

              <p className="text-sm text-gray-600">{item}</p>
            </div>
          ))}
        </div>

        <div className="flex items-center justify-between border-t border-gray-200 pt-8">
          <div className="text-xs text-gray-400">
            Dokumen dicetak pada: {new Date().toLocaleDateString("id-ID")}
          </div>

          <div className="text-right">
            <p className="text-sm font-bold text-gray-900">
              Vokara Analysis Engine
            </p>
            <p className="text-xs text-gray-500">
              Automated Policy Brief Generator
            </p>
          </div>
        </div>
      </div>

      <div className="flex justify-center gap-4">
        <button className="flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50">
          <Download className="h-4 w-4" />
          Unduh PDF
        </button>

        <button className="flex items-center gap-2 rounded-lg bg-gray-800 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-gray-900">
          <Share2 className="h-4 w-4" />
          Bagikan ke Instansi Terkait
        </button>

        <button className="bg-primary hover:bg-primary/90 flex items-center gap-2 rounded-lg px-6 py-3 text-sm font-medium text-white transition-colors">
          <CheckCircle className="h-4 w-4" />
          Tandai Selesai
        </button>
      </div>
    </div>
  );
}

function InfoCard({
  title,
  value,
  desc,
}: {
  title: string;
  value: string;
  desc: string;
}) {
  return (
    <div className="rounded-xl border border-gray-200 p-5">
      <h4 className="text-primary mb-1 text-xl font-bold">{value}</h4>
      <p className="mb-1 text-sm font-bold text-gray-900">{title}</p>
      <p className="text-xs text-gray-500">{desc}</p>
    </div>
  );
}
