"use client";

import { useAdminStore } from "@/store/useAdminStore";
import {
  ArrowLeft,
  Sparkles,
  Download,
  Share2,
  CheckCircle,
  ShieldAlert,
  Loader2,
} from "lucide-react";
import Link from "next/link";
import React, { useEffect } from "react";
interface PolicyBriefDetailPageProps {
  params: Promise<{
    id: string;
  }>;
}

function renderMarkdownText(content: unknown): string {
  if (typeof content === "string") return content;

  if (content === null || content === undefined) return "";

  if (typeof content === "object") {
    const obj = content as Record<string, any>;

    if (typeof obj.content === "string") return obj.content;
    if (typeof obj.summary === "string") return obj.summary;
    if (typeof obj.text === "string") return obj.text;
    if (typeof obj.result === "string") return obj.result;
    if (typeof obj.message === "string") return obj.message;

    return JSON.stringify(obj, null, 2);
  }

  return String(content);
}

function formatBriefContent(content: string) {
  return content.split("\n").map((line, index) => {
    const key = `${index}-${line}`;

    if (line.startsWith("# ")) {
      return (
        <h1 key={key} className="mb-6 text-3xl font-bold text-gray-900">
          {line.replace("# ", "")}
        </h1>
      );
    }

    if (line.startsWith("## ")) {
      return (
        <h2 key={key} className="mt-8 mb-3 text-xl font-bold text-gray-900">
          {line.replace("## ", "")}
        </h2>
      );
    }

    if (line.startsWith("- ")) {
      return (
        <li
          key={key}
          className="ml-6 list-disc text-sm leading-relaxed text-gray-700"
        >
          {line.replace("- ", "")}
        </li>
      );
    }

    if (/^\d+\.\s/.test(line)) {
      return (
        <li
          key={key}
          className="ml-6 list-decimal text-sm leading-relaxed text-gray-700"
        >
          {line.replace(/^\d+\.\s/, "")}
        </li>
      );
    }

    if (line.trim() === "") {
      return <div key={key} className="h-3" />;
    }

    return (
      <p key={key} className="text-sm leading-7 text-gray-700">
        {line}
      </p>
    );
  });
}

export default function PolicyBriefDetailPage({
  params,
}: PolicyBriefDetailPageProps) {
  const { id } = React.use(params);
  const {
    selectedBrief,
    error,
    isLoadingBriefs,
    fetchBriefDetail,
    clearSelectedBrief,
  } = useAdminStore();

  useEffect(() => {
    fetchBriefDetail(id).catch(() => {
      // error sudah masuk ke store
    });

    return () => {
      clearSelectedBrief();
    };
  }, [id, fetchBriefDetail, clearSelectedBrief]);

  if (isLoadingBriefs) {
    return (
      <div className="flex min-h-[400px] items-center justify-center text-sm text-gray-500">
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
        Memuat policy brief...
      </div>
    );
  }

  if (error) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
        {error}
      </div>
    );
  }

  if (!selectedBrief) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-8 text-center text-sm text-gray-500">
        Policy brief tidak ditemukan.
      </div>
    );
  }

  const content = renderMarkdownText(selectedBrief.content);

  return (
    <div className="mx-auto max-w-4xl space-y-6 pb-20">
      <div className="flex items-center justify-between">
        <Link
          href="/admin/laporan"
          className="flex items-center gap-2 text-sm font-medium text-gray-500 transition-colors hover:text-gray-900"
        >
          <ArrowLeft className="h-4 w-4" />
          Kembali ke Laporan Analitik
        </Link>

        <div className="flex items-center gap-3">
          <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">
            {selectedBrief.urgency_classification}
          </span>

          <span className="flex items-center gap-1 text-xs text-gray-400">
            <Sparkles className="h-3 w-3" />
            Generated by {selectedBrief.generated_by}
          </span>
        </div>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-8 shadow-sm md:p-12">
        <div className="mb-8 border-b-2 border-gray-900 pb-6 text-center">
          {/* <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-lg bg-gray-200">
            <ShieldAlert className="h-8 w-8 text-gray-500" />
          </div> */}

          <h2 className="text-xl font-bold tracking-wide text-gray-900 uppercase">
            Pemerintah Republik Indonesia
          </h2>

          <h3 className="text-primary mt-1 text-lg font-bold tracking-wide uppercase">
            Pusat Analisis Data Aspirasi Publik Vokara
          </h3>

          <p className="mt-2 text-sm text-gray-500">
            Sistem Terintegrasi Kebijakan Berbasis Bukti Digital
          </p>
        </div>

        <div className="mb-8 flex flex-wrap gap-6 text-sm font-medium text-gray-600">
          <p>Nomor: {selectedBrief.id.slice(0, 8).toUpperCase()}</p>

          <p>
            Tanggal:{" "}
            {new Date(selectedBrief.generated_at).toLocaleDateString("id-ID")}
          </p>

          <p>
            Sifat:{" "}
            <span className="font-bold text-red-600">
              {selectedBrief.urgency_classification}
            </span>
          </p>
        </div>

        <article className="prose prose-sm max-w-none">
          {formatBriefContent(content)}
        </article>

        <div className="mt-10 flex items-center justify-between border-t border-gray-200 pt-8">
          <div className="text-xs text-gray-400">
            Dokumen dicetak pada: {new Date().toLocaleDateString("id-ID")}
          </div>

          <div className="text-right">
            <p className="text-sm font-bold text-gray-900">
              Vokara Analysis Engine
            </p>
            <p className="text-xs text-gray-500">
              Automated Policy Brief Generator
            </p>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap justify-center gap-4">
        <button className="flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50">
          <Download className="h-4 w-4" />
          Unduh PDF
        </button>

        <button className="flex items-center gap-2 rounded-lg bg-gray-800 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-gray-900">
          <Share2 className="h-4 w-4" />
          Bagikan ke Instansi Terkait
        </button>

        <button className="bg-primary hover:bg-primary/90 flex items-center gap-2 rounded-lg px-6 py-3 text-sm font-medium text-white transition-colors">
          <CheckCircle className="h-4 w-4" />
          Tandai Selesai
        </button>
      </div>
    </div>
  );
}
